### ISSUE TITLE
issues related to model2owl

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#151]
I posted a number of issues in the "sibling project" that have an impact on this ontology. Here's a tracking list:

- [ ] https://github.com/OP-TED/model2owl/issues/77 
- [x] https://github.com/OP-TED/model2owl/issues/78 
- [x] https://github.com/OP-TED/model2owl/issues/79. Explicated as OP-TED/ePO#411
- [x] https://github.com/OP-TED/model2owl/issues/80. Similar to OP-TED/model2owl#128
- [x] https://github.com/OP-TED/model2owl/issues/81 
- [x] https://github.com/OP-TED/model2owl/issues/82 
- [x] https://github.com/OP-TED/model2owl/issues/84. Also, `sh:sparql` is part of SPARQL Advanced
- [x] https://github.com/OP-TED/model2owl/issues/85 
- [x] https://github.com/OP-TED/model2owl/issues/86 
- [x] https://github.com/OP-TED/model2owl/issues/87 
- [x] https://github.com/OP-TED/model2owl/issues/89 
- [ ] https://github.com/OP-TED/ePO/issues/458 
- [ ] https://github.com/OP-TED/model2owl/issues/91

**Comment by VladimirAlexiev** [comment]
@eprocurementontology this is the ultimate `UML2OWL` issue, please give it that label

**Comment by costezki** [comment]
This issue can be closed now. Most of the check points have been addressed and a major release of model2owl was issued. 
The remaining ones will have to be treated individually.
